language: clojure

clojure:
  - 1.10.1

install:
  - curl -O https://download.clojure.org/install/linux-install-1.10.1.466.sh
  - chmod +x linux-install-1.10.1.466.sh
  - sudo ./linux-install-1.10.1.466.sh


script:
  - make check

after_success:
  - bash <(curl -s https://codecov.io/bash) -f target/coverage/codecov.json
